name: Node.js Security Pipeline

on:
  push:

jobs:

  security-checks:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run dependency security check
        run: npm audit

      # Filesystem Scanning --- SCA
      # run: npm audit --audit-level=high
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  build:
    runs_on: ubuntu-latest
    
    steps:
      - name: Build Docker Image
        run: docker build -t demo-app .
  
      # Image Scanning
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'demo-app'
          # severity: 'CRITICAL,HIGH'
          # exit-code: '1'
          
      # Secrets Scanning  
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2

      # Misconfiguration Scan
      - name: Trivy Config Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          severity: 'HIGH,CRITICAL'
