services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: multi-cloud-rag-db
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


# Connect:
# docker exec -it multi-cloud-rag-db psql -U raguser -d ragdb

# Enable pgvector:
# CREATE EXTENSION IF NOT EXISTS vector;

# Create table:
CREATE TABLE documents (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    cloud TEXT,
    service TEXT,
    document_type TEXT,
    embedding VECTOR(1536)
);

